### ISSUE TITLE
+ ABV

### ISSUE THREAD

**Issue by lynnandtonic** [lynnandtonic/airport-codes#646]
https://twitter.com/iamiffy/status/584495170550378498

**Comment by teddylove85** [comment]
@lynnandtonic 

Content 

Nnamdi Azikiwe International Airport (IATA: ABV, ICAO: DNAA) is an international airport located in Abuja, FCT, Nigeria, and is the main airport serving the Nigerian capital city. It was named after Nigeria's first President, Dr Nnamdi Azikiwe. It consists of an international and a domestic terminal. Both terminals share the same runway. In 2009, the airport handled 3,196,438 passengers.

The Abuja Gateway Consortium signed on 13 November 2006 an US$101.1 million contract for the management of the airport over the next 25 years. The contract includes the construction of an airport hotel, private car parks, shopping malls and a bonded warehouse, totalling US$50 million, during its first five years in addition to an upfront payment of US$10 million. Total investments will according to the business plan amount to US$371 million during the period of the contract. However, president Yar'Adua revoked the contract in April 2008.

The Nigerian Civil Aviation Authority has its head office on the airport grounds.

Plans were invited for the construction of a second runway. The contract was awarded to Julius Berger for US$423 million in April, but were revoked in June due to the high cost. The Federal Government approved fresh bids for the construction of the second runway.

id = ABV
code = ABV
name = Nnamdi Azikiwe International Airport 
city = Abuja
country = Nigeria

**Comment by lynnandtonic** [comment]
Thank you, @teddylove85!
